---
title: "Direct light analysis"
author: "Mathieu Adgé"
date: "2026-08-06"
output: html_document
---

```{r setup, include=FALSE}
rm(list=ls())
library(tidyverse)
library(lubridate)
library(lme4)
library(lmerTest)
library(ggplot2)
library(cowplot)
library(performance)
library(cowplot)
library(nlme)
library(emmeans)
library(ggforce)
library(readxl)
library(hms)
library(mgcv)
library(MuMIn)
library(ggridges)
library(gratia)
```

```{r, import data}
data_direct = read.csv("../data/Light_data.csv") %>%
filter(Orientation=="Haut") %>% 
  mutate(across(c(Zone, Period, timepoint, Position,Month), as.factor), datetime=ymd_hms(datetime), hm=hour(datetime) + minute(datetime) / 60, Date = as.Date(Date), facteur=log(facteur)) %>% 
  filter(Sat_comb=="No_saturation") %>% 
  distinct(hm,Date,Zone,Position, .keep_all = TRUE)
```


```{r, final model}
### Model set-ups
data_direct <- data_direct %>% 
  mutate(DateZone = interaction(Date, Zone, drop = TRUE))

M6_gam <- gamm(facteur~Zone*Month+ Zone*Position+ s(hour_sunrise, bs ="cc", k=10, by = Zone),
              data= data_direct,
              correlation = corCAR1(form = ~ hm | DateZone/Position),
              random = list(DateZone = ~1),
              method="REML")
```


```{r}
### Appendix F1 - Verification of model assumption for the direct light model
gam.check(M6_gam$gam)
```

```{r}
### Temporal autocorrelation
M6_gam_corr <- gamm(facteur~Zone*Month+ Zone*Position+ s(hour_sunrise, bs ="cc", k=10, by = Zone),
              data= data_direct,
              random = list(DateZone = ~1),
              method="REML")
### Appendix F2 - Temporal autocorrelation of model residuals on direct light before temporal correlation correction
acf(resid(M6_gam_corr$lme, type="normalized"), lag.max = 36, main = "ACF")

### Appendix F2 - Temporal autocorrelation of model residuals on direct light after temporal correlation 
acf(resid(M6_gam$lme, type="normalized"), lag.max = 36, main = "ACF")
```
```{r}
### General output of the model 
summary(M6_gam$lme)

summary(M6_gam$gam)

r.squaredGLMM(M6_gam$lme)
```


```{r}
### Contrast by Zone, used in the graphical abstract
emm_Zone    <- emmeans(M6_gam, ~ Zone, data=data_direct)
print(emm_Zone)

contrast_Zone <- contrast(emm_Zone, method = "pairwise" ,adjust = "tukey")
print(contrast_Zone)

ct_ci <- as.data.frame(confint(contrast_Zone, level=0.95, adjust="tukey"))

ER_max = 0.13
propagation = sqrt(2*(ER_max^2))


con_Z_table <- as.data.frame(contrast_Zone) %>% 
  left_join(ct_ci) %>% 
  mutate(
    phys_detectable = (lower.CL > propagation) | (upper.CL < -propagation),
    sign_capteur = if_else(
      phys_detectable,
"Difference greater than the instrumental error",
      "Difference inferior than the instrumental error"
    ),
    filtre_sign = as.integer(phys_detectable)
  )
```


```{r}
emm_Zone_Position <- emmeans(M6_gam, ~ Zone|Position, data=data_direct)
print(emm_Zone_Position)

con_Zone_Position <- contrast(emm_Zone_Position, method = "pairwise" ,adjust = "tukey")
print(con_Zone_Position)

ct_ci <- as.data.frame(confint(con_Zone_Position, level=0.95, adjust="tukey"))

facteur_mult_tb = as.data.frame(emm_Zone_Position) %>% 
  mutate(t = -(lower.CL-emmean)/SE) %>% 
  summarise(t_mean= mean(t))  

facteur_mult = facteur_mult_tb[[1,1]]

emm_ZP_table <- as.data.frame(emm_Zone_Position) %>% 
    mutate(across(c(emmean,SE), ~ exp(.))) %>% 
  mutate(lower.CL = emmean-facteur_mult*SE, 
         upper.CL = emmean+facteur_mult*SE)

### Figure 3 - Attenuation coefficient of direct light under FPV platforms compared to unshaded, for two positions 
data_plot_ZP <- data_direct %>% 
  mutate(facteur = exp(facteur)) %>% 
  left_join(emm_ZP_table) %>% 
  mutate(Zone = factor(Zone, levels = c("6", "1", "4", "3", "5")), 
        Zone_name = case_when(Zone == 1 ~ "SH51%", 
                              Zone == 3 ~ "SH81%", 
                              Zone == 4 ~ "SH51%-UV", 
                              .default = "SH81%-UV"))

ggplot(data_plot_ZP, aes(x = facteur, y = Zone_name, fill = Position)) +

  # Ridgeline = dispersion
  geom_density_ridges(
    alpha = 0.6,
    scale = 0.9,
    rel_min_height = 0.01, 
    color= "#636363"
  ) +
  
    # Emmeans : IC
  geom_errorbar(
    aes(xmin = lower.CL, xmax = upper.CL),
    height = 0.1,
    linewidth = 1,
    color = "#636363"
  ) +

  # Emmeans : point
  geom_point(
    aes(x = emmean),
    shape = 21,
    size = 2,
    color = "#636363",
    stroke = 1
  ) +
  
  geom_vline(xintercept = 1,
             linetype = "dashed", 
             color = "#636363") + 

  scale_fill_manual(
    values = c("3" = "#66C5CCFF", "4.5" = "#DCB0F2FF"),
    labels = c("3" = "Position = (3,3)",
               "4.5" = "Position = (4.5,4.5)"),
    guide = guide_legend(title = NULL)
  ) +


  xlab("Attenuation coefficient compared to unshaded") +
  ylab("Floating PV platform") +

  theme_minimal() +
  theme(
    legend.text = element_text(size = 12),
    axis.text.x = element_text(size = 12),
    axis.text.y = element_text(size = 12),
    axis.title.x = element_text(size = 14),
    axis.title.y = element_text(size = 14),
    strip.placement = "outside",
    strip.background = element_blank(),
    panel.spacing = unit(0.5, "lines"),
    legend.position = "bottom"
  )
```



```{r}
### Appendix F3 - Results of pairwise post-hoc comparisons of hourly direct light attenuation factor 
# We construct the reference grid by fixing only the time
rg <- ref_grid(M6_gam,
               at = list(hour_sunrise = seq(1, 11, by = 1)),
               data=data_direct)  # par ex.


emm_zone_hour <- emmeans(rg, ~ hour_sunrise | Zone)

emm_ZH_table <- as.data.frame(emm_zone_hour)

diff_zone_hour <- contrast(emm_zone_hour, method = "pairwise", adjust="tukey")

ct_ci <- as.data.frame(confint(diff_zone_hour, level=0.95, adjust="tukey"))

ER_max = 0.13
propagation = sqrt(2*(ER_max^2))


con_HZ_table <- as.data.frame(diff_zone_hour) %>% 
  left_join(ct_ci) %>% 
  mutate(
    phys_detectable = (lower.CL > propagation) | (upper.CL < -propagation),
    sign_capteur = if_else(
      phys_detectable,
      "Difference greater than the instrumental error",
      "Difference inferior than the instrumental error"
    ),
    filtre_sign = as.integer(phys_detectable)
  ) %>% 
    separate(contrast, into = c("h1", "h2"), sep = "\\s-\\s") %>% 
    mutate(
    h1_num = as.numeric(str_extract(h1, "\\d+")),
    h2_num = as.numeric(str_extract(h2, "\\d+")),
    p_num = as.numeric(`p.value`),
    p_cat = case_when(
      p_num < 0.001 ~ "p < 0.001",
      p_num < 0.01  ~ "p < 0.01",
      p_num < 0.05  ~ "p < 0.05",
      TRUE          ~ "Statistically non significant"
    ),
    phys = if ("phys_detectable" %in% names(.)) phys_detectable else filtre_sign == 1,
    Zone = factor(Zone, levels = c("1", "4", "3", "5"))
  )


  zone_labels <- c(
  "1" = "Shade 51%",
  "4" = "Shade 51% - UV",
  "3" = "Shade 81%",
  "5" = "Shade 81% - UV"
)

hours <- sort(unique(c(con_HZ_table$h1_num, con_HZ_table$h2_num)))

con_HZ_table$p_cat <- factor(
  con_HZ_table$p_cat,
  levels = c("p < 0.001", "p < 0.01", "p < 0.05", "Statistically non significant")
)


ggplot(con_HZ_table, aes(x = h1_num, y = h2_num)) +
  geom_tile(aes(fill = p_cat), color = "white", linewidth = 0.25) +
  geom_point(
    data = con_HZ_table %>% filter(phys),
    shape = 4, size = 2, stroke = 1
  ) +
  facet_wrap(~Zone, labeller= labeller(Zone=zone_labels)) +
  scale_fill_manual(
    name = "p-value",
    values = c(
      "p < 0.001" = "#8B0000",
      "p < 0.01"  = "#E41A1C",
      "p < 0.05"   = "#FDB863",
      "Statistically non significant"             = "grey85"
    )) +
  coord_equal() +
  labs(
    x = "Hour after sunrise",
    y = "Hour after sunrise",
    caption = "Crosses indicate differences exceeding instrumental uncertainty (physically significant)."
  ) +
  scale_x_continuous(
  breaks = sort(unique(con_HZ_table$h1_num)),
  labels = function(x) as.integer(x)
) +
scale_y_continuous(
  breaks = sort(unique(con_HZ_table$h2_num)),
  labels = function(x) as.integer(x)
) +
  theme_minimal(base_size = 11) +
  theme(
    panel.grid = element_blank(),,
    strip.text = element_text(face = "bold")
  )

```

```{r}
### Appendix F4 - Results of pairwise post-hoc comparisons of monthly direct light attenuation factor 
emm_Month_Zone <- emmeans(M6_gam, ~ Month|Zone, data=data_direct)
print(emm_Month_Zone)

con_Month_Zone <- contrast(emm_Month_Zone, method = "pairwise" ,adjust = "tukey")
print(con_Month_Zone)

ct_ci <- as.data.frame(confint(con_Month_Zone, level=0.95, adjust="tukey"))

emm_MZ_table <- as.data.frame(emm_Month_Zone) 

ER_max = 0.13
propagation = sqrt(2*(ER_max^2))


con_MZ_table <- as.data.frame(con_Month_Zone) %>% 
  left_join(ct_ci) %>% 
 mutate(
    phys_detectable = (lower.CL > propagation) | (upper.CL < -propagation),
    sign_capteur = if_else(
      phys_detectable,
      "Difference greater than the instrumental error",
      "Difference inferior than the instrumental error"
    ),
    filtre_sign = as.integer(phys_detectable)
  ) %>% 
  separate(contrast, into = c("Month1", "Month2"), sep = "\\s-\\s") %>% 
    mutate(
    Month1_num = as.numeric(str_extract(Month1, "\\d+")),
    Month2_num = as.numeric(str_extract(Month2, "\\d+")),
    Month1_lab = factor(
      Month1_num,
      levels = 1:12,
      labels = c(
        "January", "February", "March", "April", "May", "June",
        "July", "August", "September", "October", "November", "December"
      )
    ),
    Month2_lab = factor(
      Month2_num,
      levels = 1:12,
      labels = c(
        "January", "February", "March", "April", "May", "June",
        "July", "August", "September", "October", "November", "December"
      )
    ),
    p_num = as.numeric(`p.value`),
    p_cat = case_when(
      p_num < 0.001 ~ "p < 0.001",
      p_num < 0.01  ~ "p < 0.01",
      p_num < 0.05  ~ "p < 0.05",
      TRUE          ~ "Statistically non significant"
    ),
    phys = if ("phys_detectable" %in% names(.)) phys_detectable else filtre_sign == 1,
    Zone = factor(Zone, levels = c("1", "4", "3", "5"))
  )

  zone_labels <- c(
  "1" = "Shade 51%",
  "4" = "Shade 51% - UV",
  "3" = "Shade 81%",
  "5" = "Shade 81% - UV"
)
# 2) Toutes les heures
months <- sort(unique(c(con_MZ_table$Month1_lab, con_MZ_table$Month2_lab)))


# 3) Ordonner les catégories de p-values (légende)
con_MZ_table$p_cat <- factor(
  con_MZ_table$p_cat,
  levels = c("p < 0.001", "p < 0.01", "p < 0.05", "Statistically non significant")
)

# 4) Plot
ggplot(con_MZ_table, aes(x = Month1_lab, y = Month2_lab)) +
  geom_tile(aes(fill = p_cat), color = "white", linewidth = 0.25) +
  geom_point(
    data = con_MZ_table %>% filter(phys),
    shape = 4, size = 2, stroke = 1
  ) +
  facet_wrap(~Zone, labeller= labeller(Zone=zone_labels)) +
  scale_fill_manual(
    name = "p-value",
    values = c(
      "p < 0.001" = "#8B0000",
      "p < 0.01"  = "#E41A1C",
      "p < 0.05"  = "#FDB863",
      "Statistically non significant" = "grey85"
    ),
    na.value = "grey95"
  ) +
  coord_equal() +
  labs(
    x = NULL, y = NULL,
    caption = "Crosses indicate physically significant differences (above instrumental uncertainty)."
  ) +
  theme_minimal(base_size = 11) +
  theme(
    panel.grid = element_blank(),
    axis.text.x = element_text(angle = 45, hjust = 1),
    strip.text = element_text(face = "bold")
  )
```

